# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b542c64b954d0b9e9d2bc8b2336c32414709ce6264483bfb603d81c7d286c38c9e8f95a413274f645b5fb9614b01713702e7882ccb3306776708e2510c2bfe5

test:
  secret_key_base: 45d2b44fdc297b4e56ea0878839217fa2a69c63224fb2e211cbf03a68352339a30bfdf400b0c244bc91f2c21cec76c197fcd464e5aa628b4afd464149cb1314b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
